### ISSUE TITLE
Could you add a custom distribution?

### ISSUE THREAD

**Issue by noejn2** [rok-cesnovar/stan-distributions#21]
My custom distribution is a variation of the beta distributions, so it would only require you to add a few lines (and a new variable). I would do it, but I do not know HTML.

**Comment by rok-cesnovar** [comment]
Yeah, it should easily be doable. Do you have a specific one in mind or maybe Stan code?

**Comment by noejn2** [comment]
Below I show the custom distribution I use in my Stan script. Please, notice that this is in logs. It is a parametrization of the beta distribution which is not bounded at 1, but at yupp (usually useful at my work at about 300), and it has a location and dispersion parameter. Notice that the location parameter is bounded between 0 and 1, and the dispersion parameter must be greater than 0 (the latter is usually useful for my work at about 120. I had to do some quick tweaks since it was actually returning the sum of log-likelihoods rather than a single value. I also have it written in case it is more useful for you.

```
functions { 
  // Unbounded beta function with location and dispersion parameters
    real betaUnbounded_lpdf(real y, real yupp, real<lower=0,upper=1> mu, real<lower=0> phi) {

        // Components
        real denominator = (phi - 1)*log(yupp);
        logGamma = lgamma(phi)-(lgamma(mu*phi) + lgamma((1-mu)*phi));
        numerator = (mu*phi-1)*log(y) + ((1-mu)*phi-1)*log(yupp - y);

        real logLike = numerator - denominator + logGamma;

        return(logLike);
    }
}
```

**Comment by rok-cesnovar** [comment]
https://rok-cesnovar.github.io/stan-distributions/beta_unbounded

Let me know if it looks good, I will add it to the front-page list if it does. Thanks!

**Comment by noejn2** [comment]
Beautifully done! Thanks a lot!

**Comment by rok-cesnovar** [comment]
Thank you. 

Added to README - https://github.com/rok-cesnovar/stan-distributions#custom-distributions

I also added the Stan code to the distribution page.

I am closing this now.
